### ISSUE TITLE
How to implement @nodecontextmenu?  No documentation

### ISSUE THREAD

**Issue by robogeek** [holiber/sl-vue-tree#16]
In the application I'm pondering it would be useful for the tree viewer to have a context menu.

The documentation doesn't say what to do, and neither do the demos.

I see in the source code that `nodecontextmenu` is emitted, and I am successfully receiving the event, but don't know what to do afterward.

**Comment by holiber** [comment]
Hey. Check the example https://holiber.github.io/sl-vue-tree/demo/index - it has a context menu handling.
