### ISSUE TITLE
IE11 problem

### ISSUE THREAD

**Issue by savenko** [holiber/sl-vue-tree#17]
Hello!
In Vue Cli 3 in production mode plugin do not worked in IE 11. Reason: arrow function not transform.
Discussions here:  https://forum.vuejs.org/t/vue-cli-3-and-ie-11/39933

**Comment by holiber** [comment]
Hey, thanks for the report. Yeah, I'm going to add the babel transpiler to resolve that

**Comment by Substr** [comment]
@holiber Hi, any chance of this getting looked at soon? We ran across this problem in our app and are really dependent on sl-vue-tree at the moment. Thanks.

**Comment by holiber** [comment]
@Substr Hi. Will try to find time to look into IE11 issues this week. PRs are also appreciated

**Comment by holiber** [comment]
@savenko @Substr enjoy https://github.com/holiber/sl-vue-tree#ie-11-support
