### ISSUE TITLE
@nodeclick is not firing

### ISSUE THREAD

**Issue by notchris** [holiber/sl-vue-tree#2]
First off, this lib is great, thank you!

I'm having trouble getting @nodeclick or @select to fire correctly. @select seems to fire, but does not return the target node. @nodeclick does not fire.

`<sl-vue-tree @nodeclick="test(node)" :allowMultiselect="false" v-model="nodes">`

also tried...

`<sl-vue-tree v-on:nodeclick="test(node)" :allowMultiselect="false" v-model="nodes">`

Thanks again! Let me know if I'm doing something wrong.

- Chris

**Comment by holiber** [comment]
Sorry for the late response and thanks for the report. I can confirm that this issue exists. I'm going to create a PR. For now, the workaround is using the `select` event instead.
`<sl-vue-tree @select="selectHanlder" v-model="nodes">`

**Comment by holiber** [comment]
fixed in `v1.5.0`
