### ISSUE TITLE
Handle selecting nodes via data

### ISSUE THREAD

**Issue by Alex-Sokolov** [holiber/sl-vue-tree#4]
Example:
```
<sl-vue-tree v-model="nodes" :allow-multiselect="false"></sl-vue-tree>
```
and somewhere `selectedNode` method:
```
selectedNode(node) {
  node.isSelected = true
}
```

When selecting node in sidebar — all ok, but if we select one node, and later somewhere change `isSelected` in nodes — will be two selected nodes.

How to handle selecting nodes outside component, from data?

**Comment by holiber** [comment]
Hi. You can use `traverse` method to change the original model:
````javascript
slVueTree.traverse((node, nodeModel, path) => {
    Vue.set(nodeModel, 'isSelected', true);
})
````
Also you can try to use `select` method
````javascript
slVueTree.select(node)
````
However this is an undocumented method and it is going to be changed in next versions

**Comment by holiber** [comment]
@Alex-Sokolov you can upgrade and try `select(path)` method from `v1.5.0`
