### ISSUE TITLE
Lost old data  after toggle visibility

### ISSUE THREAD

**Issue by kossa** [holiber/sl-vue-tree#43]
Hello,

I have a categories system, with : id, name, parent_id, visible_on_menu

I put the name into title, id and visible_on_menu under data, the problem is once I update the visibility I lost the id
I'm using this : https://github.com/holiber/sl-vue-tree/blob/master/demo/dark-theme.html#L134

**Comment by kossa** [comment]
![image](https://user-images.githubusercontent.com/1175584/51436898-a24a6480-1c95-11e9-8de2-b0aed9754e09.png)

**Comment by holiber** [comment]
Thanks for reporting this

**Comment by holiber** [comment]
I can't find any issues here. How do you update your `data` field?
If you're using `updateNode` method, keep in mind that it doesn't patch the node recursively. It simply updates the node with `Object.assign(nodeModel, patch);` - line 650

**Comment by kossa** [comment]
I using the code on the demo, currently I added manualy the id `        slVueTree.updateNode(node.path, {data: { visible: visible, id: node.data.id}});
` : 
```
  ...
    toggleVisibility: function (event, node) {
        const slVueTree = this.$refs.slVueTree;
        event.stopPropagation();
        const visible = node.data && node.data.visible !== true;
        slVueTree.updateNode(node.path, {data: { visible: visible, id: node.data.id}});

        console.log('Toggle visible', node.data.id, visible);
      },

```

**Comment by holiber** [comment]
Just tested this code in `test_toggle_visibility` branch. It works for me. Are you up to date with the last version?

**Comment by kossa** [comment]
Alright you have to add the id manually :)

https://github.com/holiber/sl-vue-tree/commit/c9882584ff369131b7e99274de2ea419613c5f8b#diff-ecfbcb1c4778b2fc8a2fb4165903478eR138

**Comment by kossa** [comment]
Each time you change the visible property, you have to add all others data, for now I fixed the issue like that

**Comment by holiber** [comment]
Yes, there is no special method to patch the data field, you can only replace the whole object. In spite of this, you always have an old data object in the function's arguments. Just use [spread syntax](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_syntax) or `Object.assign` for convenience
```js
    toggleVisibility: function (event, node) {
        ....
        slVueTree.updateNode(node.path, {data: { ...node.data, visible: visible}});
        ....
      },

```

**Comment by kossa** [comment]
Great thank you for help, I'm very happy that the plugin was integrated successfully with [lazychaser/laravel-nestedset](https://github.com/lazychaser/laravel-nestedset/issues/333)
