### ISSUE TITLE
Adding a directive for node leaf's title container

### ISSUE THREAD

**Issue by rreckonerr** [holiber/sl-vue-tree#47]
I'm trying to add a tooltip for node leafs. The idea is to display leafs full title on hover, since leafs title is too long and has to be truncated. I'm trying to combine SlVueTree with [v-tooltip](https://github.com/Akryum/v-tooltip), but I can't figure out how to add `v-tooltip="Some message"` directive to leaf's title container.

**Comment by holiber** [comment]
Did you try to override the `title` slot?

```html
<sl-vue-tree v-model="nodes">
    <template slot="title" slot-scope="{ node }">

      <div v-tooltip="Some message">
        {{ node.title }}
      </div>
      
    </template>
</sl-vue-tree>
```

**Comment by rreckonerr** [comment]
@holiber works great! Thank you!
```vue
    <div v-if="node.isLeaf" v-tooltip="node.title">
        {{ node.title }}
    </div>
    <div v-else>
        {{ node.title }}
    </div>
```
