### ISSUE TITLE
i wan edit a title after click 

### ISSUE THREAD

**Issue by nazaninhesari** [holiber/sl-vue-tree#48]
i wan edit a title after click a node ,
example node 1 >>> node 2 rename

**Comment by nazaninhesari** [comment]
i solved this

`this.$refs.slVueTree.insert({node:thisnode,placement: "inside"}, {title: "Dragged Item"});
`

**Comment by nazaninhesari** [comment]
how i can update a node

`this.$refs.slVueTree.updateNode({node:thisnode}, {title: "changed Item"});
`

??

**Comment by nazaninhesari** [comment]
i sloved this by
`this.$refs.slVueTree.updateNode(node.path, { ...node, title: 88888888});
`
then i need change id in data
`			this.$refs.slVueTree.updateNode(node.path,{ ...node.data, id: 999});
`
it not changed id !

**Comment by holiber** [comment]
You're not updating the `data` in your exaple

The correct way is
```js
this.$refs.slVueTree.updateNode(node.path, {  data: {id: 999} });
```

**Comment by nazaninhesari** [comment]
thanks work fine
