### ISSUE TITLE
how add inserted in last children

### ISSUE THREAD

**Issue by nazaninhesari** [holiber/sl-vue-tree#49]
how add inserted in last children
			`	this.$refs.slVueTree.insert({node:node,placement: "inside"}, { title:node.title,code:node.code});				
`
this code add in first items

**Comment by holiber** [comment]
you can update the node children:
```js
const nodePath = [1, 2, 3];
slVueTree.updateNode(
  nodePath,
  {children: [ ...slVueTree.getNode(nodePath ).children, { title: 'A New Child2'}]}
)
```

**Comment by akolnati** [comment]
just what i have been looking for... Thanks @holiber
