### ISSUE TITLE
Can't drag node to non-parented position if last node is nested

### ISSUE THREAD

**Issue by zetokore** [holiber/sl-vue-tree#5]
Nice work!  Noticed one issue-

![image](https://user-images.githubusercontent.com/7066726/41450472-360f3920-7025-11e8-8388-8758d16274f2.png)

In the above example, try dragging "Folder6" to the end of the list in a non-parented position, it's not possible.

**Comment by johndatserakis** [comment]
I noticed this as well in my app. Here's a gif of the issue:

![Gif](https://thumbs.gfycat.com/WiltedAltruisticAustralianshelduck-size_restricted.gif)

As you can see, when I go to drag `Note 4` to the very bottom to make it a parent - it gets placed as a child of `Copy Of Note 4`. I'm sure this is something that can be fixed.

**Comment by holiber** [comment]
![reordering](https://user-images.githubusercontent.com/3768346/41573146-25d54bcc-7330-11e8-9c9c-4facf7349459.gif)
^ @SteveS123 @johndatserakis  I hope this is behavior that you expected. Implemented in `v1.5.1`

**Comment by johndatserakis** [comment]
Awesome thank you!
