### ISSUE TITLE
Programmatically selecting prev/next in tree

### ISSUE THREAD

**Issue by Alex-Sokolov** [holiber/sl-vue-tree#6]
Is it possible to move selection by code?

For example, assume that selected `Image Block 3`:

<img width="244" alt="2018-06-19 11 52 21" src="https://user-images.githubusercontent.com/4497128/41587233-5afbf4b8-73b7-11e8-90de-0d0c60506d8a.png">

If we call method up — selection moved to `Image Block 2`
If we call method down — selection moved to `Text Block 4`

Thanks!

**Comment by holiber** [comment]
That looks like a good proposal. However, it is not clear how `up` and `down` methods are going to work with multiple selections. So I'm going to figure out some more flexible solution.

**Comment by holiber** [comment]
@Alex-Sokolov you can use `getPrevNode` and `getNextNode` methods from `v1.6.0`. See example `keyboardcontrols.html` in the `demo` folder.

**Comment by Alex-Sokolov** [comment]
@holiber Thanks! :)
