### ISSUE TITLE
Path of targetNode is old

### ISSUE THREAD

**Issue by betterRunner** [holiber/sl-vue-tree#62]
Hi there,
the path of targetNode in the callback nodeDropped is the old path instead of the one after the drop, that makes the updateNode function unable to use. How to fix this?
Thanks.

**Comment by sarimabbas** [comment]
I seem to be running into this problem as well. Was this fixed? Thank you!

**Comment by vitalik-lapushkin** [comment]
I use traverse() method something like this:
```vue.js
dropHandler([node]) {
  this.$refs.slVueTree.traverse((traverseNode) => {
    let proceed = true;
    if (node.data.id === traverseNode.data.id) {
      console.log(traverseNode);
      proceed = false;
   }
    return proceed;
  });
}
```
traverseNode will have refreshed state.
Before that i add unique id in nodes data field.
